name: Produce the documentation of the repository
on: [push]

jobs:
  SelfDocumentation:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - run: cd project && chmod +x ./ppaperwork.sh && ./ppaperwork.sh -r

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: documentation
          path: project/documentation

      - run: echo "🎉 finished !"
